[project]
name = "my-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "google-api-python-client>=2.167.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
